### ISSUE TITLE
jdx:licenseRequirement, jdx:licenseType not in .ttl?

### ISSUE THREAD

**Issue by robinsonkwame** [jobdataexchange/Data-Modeling#11]
[jdxcontext.json](https://github.com/jobdataexchange/Data-Modeling/blob/874976befcadffaea8a0fba58df1d765439177d5/jdxcontext.json) lists `jdx:licenseRequirement` and `jdx:licenseType` but I do not see corresponding definitions in the [jdxTerms.json](https://github.com/jobdataexchange/Data-Modeling/blob/874976befcadffaea8a0fba58df1d765439177d5/jdxTerms.json), should I expect to see one?

**Comment by stuartasutton** [comment]
@robinsonkwame, the context file needs updating. It's on my Saturday agenda. However, the [latest version of the domain model](https://drive.google.com/open?id=10anKbHK5CK5yIx2EM0THeZWPtv_8HCFp) changed the jdx:License class tp jdx:Credential and the jdx:licenseRequirement to jdx:credentialRequirement.  There is still some debate about this change introducing some confusion between the jdx:Credential and jdx:Education.

**Comment by robinsonkwame** [comment]
Great to know, thanks. I can definitely think of cases where Education might be conflated with Credential, interesting food for JDX thought.
