### ISSUE TITLE
Set schema.org .ttl reference to http instead of https

### ISSUE THREAD

**Issue by robinsonkwame** [jobdataexchange/Data-Modeling#14]
This came up as a parsing implementation related issue (in Python's rdflib library) but the `jsonTerms.ttl` file that I use to determine what JDX schema properties there are has the `schema` prefix referring to  `https://schema.org`.

The issue is `https://schema.org` has a `vocab` reference as `http://schema`, note the lack of `https`, which is then used to set the namespace of any `json-ld` document that references `https://schema.org` via `@context`.

So, in effect, the namespace reference and namespace source are different; see both https://github.com/RDFLib/rdflib-jsonld/issues/59 and https://github.com/w3c/web-annotation/issues/193 for related issues. For reference application development, it would great if we could change,

`@prefix schema: <https://schema.org/> .`
to
`@prefix schema: <http://schema.org/> .`

**Comment by stuartasutton** [comment]
Fine with me. I'll update the .ttl

**Comment by robinsonkwame** [comment]
Excellent!
