### ISSUE TITLE
Access to JDX Servers

### ISSUE THREAD

**Issue by jeannekitchens** [jobdataexchange/Data-Modeling#22]
@matthewgee questions came up in GitHub and in recent team meetings about staging and production environments and server access.  @westfall104 let us know that BrightHive has been provided access to possibly the domain provider and to servers.  This is to confirm to what access has and hasn't been established and I'm going to link to this with the next meeting so we know how the environments are setup.

**Comment by robinsonkwame** [comment]
@stuartasutton @jkitchensSIUC Happy to report that BrightHive has identified our jdx.org server access.

This impacts Issue #19 where we are working on setting up a DNS entry and serving the `jdxcontent.json`. It is assumed that we can create subdomains for staging, production environments as well which should cover this issue. (@tplagge)

**Comment by stuartasutton** [comment]
@robinsonkwame,  can @jkitchensSIUC and I assume that getting this set up is in progress? Are you doing the work? I'm heading into the weekend (my most productive work time) and it would be great to have the actual the context file resolving before we encourage the ConcentricSky team to fully tackle the job description json-ld.

**Comment by robinsonkwame** [comment]
@stuartasutton  correct, this is being worked, currently we have uploaded the `jdxcontext` file to https://s3.us-east-2.amazonaws.com/jdx-data-model/jdxcontext.json and are working on the dns/HTTPS redirect right now. Will update when everything's up.

**Comment by stuartasutton** [comment]
Very good, Kwame. Thanks!

**Comment by robinsonkwame** [comment]
Happy to report that you can now access the jdxcontext.json file from jobdataexchange.org: http://jobdataexchange.org/jdxcontext.json

**Comment by stuartasutton** [comment]
Thanks, Kwame!
