### ISSUE TITLE
JS+_Full/jdxTerms.ttl and JS+_Full/jdxTerms.json are out of synch

### ISSUE THREAD

**Issue by philbarker** [jobdataexchange/Data-Modeling#34]
JS+_Full/jdxTerms.ttl and JS+_Full/jdxTerms.json should be two representations of the same schema, but fixes to issues found during creation of HROpen JSON Schema were applied to the .json version only, and so the two differ on the following 

- [ ] ttl uses vann:usageNote not skos:scopeNote (*)
- [ ] ttl still has grammatical query in definition of  schema:validThrough "The date after when [which?] ..."
- [ ] ttl has dct:identifier "schema:validThrough" for  schema:validFrom
- [ ] ttl has rdfs:domain jdx:AnnnotatedDefinedTerm  for jdx:annotation
- [ ] ttl has annotatedTerm property, json does not
- [ ] ttl has terms from asn, json has none. The terms are asn:ProgressionModel asn:Rubric asn:RubricCriterion asn:benchmark asn:criterionFor asn:hasProgressionModel, asn:hasScope and so on; also dct:language used in asn
- [ ] ttl has two references to jdx:Organization that should be schema:Organization
- [ ] ttl has schema:scaleAnnotation should be jdx:scaleAnnotation
- [ ] ttl has mix of PostingInstruction and PostingInstructions (should be latter)
- [ ] ttl has ref to JobCompetenctProfile (should be JobCompetencyProfile )
- [ ] ttl has refs to jobPosting and jdx:jobDescription  jdx:jobCompetencyProfile (should be **J**ob____ ) 
- [ ] ttl has ref to jdx:CompetencyProfile which should be jdx:JobCompetencyProfile
- [ ] and schema:MonetaryValueDistribution which should be schema:MonetaryAmountDistribution
- [ ] jdx:Description should be jdx:JobDescription
- [ ] jdx:Person in the domain of jdx:provider (deleted in json, but probably should have been schema:Person) (**)
- [ ] schema:DefinedTermSet in json but not in ttl
- [ ] schema:Person deleted from json but not from ttl (**)
- [ ] ttl has one xsd:anyUri should be xsd:anyURI

Comments / questions:
(*) I am inclined to keep the usage notes about which properties were used in the pilot, they seem like they might be useful
(**) I think these were removed because the property class relationship was broken by use of jdx:Person instead of schema:Person.
Also: is the wholesale removal of ASN just a consequence of not being able to model references to external RDF entities in JSON Schema?

**Comment by stuartasutton** [comment]
Phil, because the focus was not on maintaining the ttl while the specification was in considerable flux, the "pilot" annotation was not consistently maintained. Person was deleted from the model because it was outside the scope of the JDX phase 1; and, as a result, no real development occurred. The scope of HR Open and the data points available in terms of Person as employee or candidate in  HR systems are very, very extensive and we were not going to plunge in there without the existence of use cases.  Person was in the model as an abstract class without properties and was removed because HR Open couldn't use them.

**Comment by philbarker** [comment]
Thanks @stuartasutton that's useful to know.  If the ASN declarations are not needed then it might make sense to re-generate the ttl file from the jdxTerms.json file automatically using one of the conversions tools. I'll have a look to check whether they produce human-firendly output for this.

**Comment by stuartasutton** [comment]
They generate decent ttl, but frequently not in alpha order

**Comment by philbarker** [comment]
Stuart, I used https://rdf-translator.appspot.com/ which I think did a decent job. Terms are alphabetical by namespace, with Classes first. So PR #35 makes all the changes listed above.
