### ISSUE TITLE
Recommended updates to the Job Master (and related domain model breakdown)

### ISSUE THREAD

**Issue by acunsolo** [jobdataexchange/Data-Modeling#4]
@stuartasutton adding this as an issue for you. Based on email sent on Sept 26

Assuming that we want to use HR-JSON 4.1 as a basis to talk about the main transport of job / position opening, and that the focus of the JDX is mostly around the defined term/scaled association, we would recommend that the domain model of Job Master and related properties be broken down as follow:

- Rename JobMaster —> Position Opening for easier alignment to HROpen terminology
- Position Opening focuses on the identifying data
  - Inside of PositionOpening, PositionProfile focuses on the position core content
  - Inside of PositionProfile  
    - PositionLocation focuses on location of job
    - PositionOrganizations focuses on the companies
    - PositionFormattedDescriptions focuses on the unstructured job text/sections
    - PostingInstructions focused on distribution to 1 or more channels (i.e. job boards, diversity sites, etc)
    - Categorization/Classification items (i.e. Job categories, Career levels, Position types). While these are on the Position Profile in the model, I see that these could easily (because of the 1..many) be attached to the PositionOpening top level instead)
- For the purpose of this project, I don’t think we need to focus on the detailed breakdown that HR-JSON has today on job requirements as this should be covered and fully mapped in the definedTerms
- However, for completeness, I’ve listed some of the breakdowns below for these other items (i.e. education requirements, experience requirements, position competencies, etc)

A more detailed breakdown below:
- Position Opening
  - id
  - language 
  - status Code (i.e. active, complete, incomplete, onhold)
  - approval Status code 
  - Posting Requester (basically person/contact instantiating exchange)
    - Name (i.e. organization doing the posting - can be a staffing firm)
    - (1..many) PersonContacts (includes name, address, phone)
  - (1..many) Position Profile - Position Opening has 1 to many, Position Profile
    - Profile ID
    - External ID
    - Position Title
    - (1..many) Position Locations
      - Location name
      - Reference location
      - Address (type which includes full address and geo location)
    - Position Period (start and end date)
    - Schedule type codes
    - Working periods
    - Offered Remuneration (salary)
    - (1..many) PositionOrganizations
      - Id
      - Name
      - Responsibility code (i.e. parent, holding, operating)
      - Domain name
    - (1..many) PositionFormattedDescriptions (like sections on a job description)
      - description id
      - title
      - content (text and/or HTML)
    - Quantity
    - Travel Requirements
    - (1..many) Working languages (could be modelled in definedTerms)
    - Qualification summary
    - (1..many) Position competencies (could be modelled in definedTerms)
      - id (which includes full reference to a taxonomy)
      - name
      - Required proficiency level
      - Desired proficiency level
      - Weight
    - Education requirements (could be modelled in definedTerms)
      - educationLevelCode
      - iscedEducationLevelCode
      - degreeTypeCode
      - (1..many) programs
      - (1..many) programConcentrations
      - (1..many) institutions
      - (1..many) descriptions
    - Experience summary (could be modelled in definedTerms)
      - (1..many) experience category types
      - Category code
      - measure
      - levelCode
    - (1..many) descriptions
    - (1..many) licenses (could be modelled in definedTerms)
    - (1..many) Job categories (could be put at PositionOpening Level) (could be modelled in definedTerms)
    - (1..many) Career levels (could be put at PositionOpening Level) (could be modelled in definedTerms)
    - (1..many) Position types (could be put at PositionOpening Level)
    - (1..many) Posting Instructions
      - Channel id
      - Start date
      - End date
      - Template id
      - Branding id
      - (1..many) Posting Option codes
      - (1..many) application methods
        - instructions
        - Application URL
        - Application email
        - Application SMS
        - Application Phone
        - In Person application
        - Application close date

**Comment by fezick** [comment]
👍
